sodo: required
services:
  - docker

before_install:
  - docker build --tag volodymyrkolomiiets/docker-flask-test -f Dockerfile.dev .

scrtipt:
  - docker run -d volodymyrkolomiiets/docker-flask-test
  - docker exec volodymyrkolomiiets/docker-flask-test pytest